### PR TITLE
feat: pwa functionality

### LINKED ISSUE #26: Add pwa settings in the site so we can use it as a pwa

### PR DESCRIPTION
**Pull request by mathdebate09**
letss goo service worker and manifest done
closes #26

### CODE REVIEW

**Comment by Mihir867** [comment]
Letsss goo

**Comment by mathdebate09** [comment]
@Mihir867 no...
ek aur commit karna padega, chota sa hi hai

prod broke, service worker ko mnaually extra space allot

**Comment by Mihir867** [comment]
> @Mihir867 no...
> ek aur commit karna padega, chota sa hi hai
> 
> prod broke, service worker ko mnaually extra space allot
> 

You have prettier on save kya ??

**Comment by mathdebate09** [comment]
> > @Mihir867 no...
> > ek aur commit karna padega, chota sa hi hai
> > prod broke, service worker ko mnaually extra space allot
> 
> You have prettier on save kya ??

wait, ha ;-;

**Pull request merged**
